name: Docker Image Build

on:
  push:
    branches:
      - main

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker build . -t indexing
